language: php

php:
    - 7.0

before_script:
    - chmod +x db
    - composer install --prefer-source
    - composer require "satooshi/php-coveralls:^1.0"

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

script:
    - php -S localhost:8000 -t src/Api/ &
    - mkdir -p build/logs
    - vendor/bin/phpunit -c phpunit.xml.dist --coverage-text --coverage-clover ./build/logs/clover.xml
    - bin/check-code-cov

after_script:
    - php vendor/bin/coveralls -v
