language: php

php:
    - 7.0

before_script:
    - composer install --prefer-source
    - composer require "satooshi/php-coveralls:^1.0"

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit -c phpunit.xml.dist --coverage-text --coverage-clover ./build/logs/clover.xml
    - bin/check-code-cov

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi

  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

after_script:
    - php vendor/bin/coveralls -v
